# -*- coding: utf-8 -*-
"""OptimizedBubbleSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFdfg2oY0qWMmU_ME39lGwnMaSNlLMPE
"""

def optimized_bubbleSort(arr):
    n = len(arr)
    pass_count = 0
    array_accesses = 0
    swaps = 0

    start = 0
    end = n - 1

    print(f"\nOriginal array: {arr}")

    while start < end:
        lastSwapped = 0

        # Left-to-right pass (→)
        for i in range(start, end):
            array_accesses += 2  # arr[i] and arr[i + 1]
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                array_accesses += 4  # 2 reads, 2 writes for the swap
                swaps += 1
                lastSwapped = i
        end = lastSwapped
        pass_count += 1
        print(f"Pass {pass_count} (→): {arr}")

        if start >= end:
            break

        lastSwapped = 0

        # Right-to-left pass (←)
        for i in range(end - 1, start - 1, -1):
            array_accesses += 2  # arr[i] and arr[i + 1]
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                array_accesses += 4  # 2 reads, 2 writes for the swap
                swaps += 1
                lastSwapped = i + 1
        start = lastSwapped
        pass_count += 1
        print(f"Pass {pass_count} (←): {arr}")

    print(f"\nTotal passes: {pass_count}")
    print(f"Total array accesses: {array_accesses}")
    print(f"Total swaps performed: {swaps}")
    print(f"Sorted array: {arr}")

user_input = input("Enter numbers separated by spaces: ")
try:
    arr = [int(num) for num in user_input.split()]
    optimized_bubbleSort(arr)
except ValueError:
    print("Error: Please enter only numbers separated by spaces.")

# Sample Input 1: 54 23 87 12 35 76 41 9 63 30 5 48 97 18 26 69 84 3 15 60
# Sample Input 2: 1 2 3 4 37 12 48 25 6 19 50 10 39 20 33 26 15 41 2 44 30